version: '3.3'

services:
  sut:
    build:
      context: test
      dockerfile: Dockerfile
  thunder-php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKERFILE_DIR: .
    command: ["echo", "-e", "<?php\necho 'Thunder-PHP';", ">", "index.php", ";", "php", "-S", "0.0.0.0:8080", "index.php"]
