#!/bin/bash
#
# Server Thunder

# Set all runtime environments for "thunder" user
echo -e "\n" >> /home/thunder/.profile;
echo -e "export DB_HOST=\"$DB_HOST\"\n" >> /home/thunder/.profile;
echo -e "export DB_NAME=\"$DB_NAME\"\n" >> /home/thunder/.profile;
echo -e "export DB_USER=\"$DB_USER\"\n" >> /home/thunder/.profile;
echo -e "export DB_PASS=\"$DB_PASS\"\n" >> /home/thunder/.profile;
echo -e "export DB_PORT=\"$DB_PORT\"\n" >> /home/thunder/.profile;
echo -e "export DB_DIVER=\"$DB_DIVER\"\n" >> /home/thunder/.profile;

echo -e "export BRANCH_NAME=\"$BRANCH_NAME\"\n" >> /home/thunder/.profile;
echo -e "export THUNDER_PROJECT=\"$THUNDER_PROJECT\"\n" >> /home/thunder/.profile;
echo -e "export ADDITIONAL_PHP_PACKAGES=\"$ADDITIONAL_PHP_PACKAGES\"\n" >> /home/thunder/.profile;

# Build, install and serve Thunder
su - thunder -c "thunder-php-build && thunder-php-install && thunder-php-serve"
