#!/bin/bash
#
# Install Thunder

# Adjust settings.php
cat <<EOF >> /home/thunder/www/docroot/sites/default/settings.php

if (!isset(\$databases)) {
  \$databases = [];
}

\$databases['default']['default'] = [
  'prefix' => '',
];

EOF

HASH_SALT="$(openssl rand -hex 32)"
echo -e "\$settings['hash_salt'] = '${HASH_SALT}';\n\n" >> /home/thunder/www/docroot/sites/default/settings.php

echo -e "\$databases['default']['default']['host'] = '${DB_HOST}';\n" >> /home/thunder/www/docroot/sites/default/settings.php
echo -e "\$databases['default']['default']['port'] = '${DB_PORT}';\n" >> /home/thunder/www/docroot/sites/default/settings.php
echo -e "\$databases['default']['default']['database'] = '${DB_NAME}';\n" >> /home/thunder/www/docroot/sites/default/settings.php
echo -e "\$databases['default']['default']['username'] = '${DB_USER}';\n" >> /home/thunder/www/docroot/sites/default/settings.php
echo -e "\$databases['default']['default']['password'] = '${DB_PASS}';\n" >> /home/thunder/www/docroot/sites/default/settings.php
echo -e "\$databases['default']['default']['namespace'] = 'Drupal\\Core\\Database\\Driver\\${DB_DIVER}';\n" >> /home/thunder/www/docroot/sites/default/settings.php
echo -e "\$databases['default']['default']['driver'] = '${DB_DIVER}';\n" >> /home/thunder/www/docroot/sites/default/settings.php

# Remove write for settings.php
chmod a-w /home/thunder/www/docroot/sites/default/settings.php

# Install and required modules
cd /home/thunder/www/docroot

../bin/drush -y si thunder --debug
../bin/drush cr
