#!/bin/bash
#
# Build Thunder

# Install branch of thunder distribution
composer create-project thunder/thunder-project:${THUNDER_PROJECT} ~/www --no-interaction --stability dev --no-install
cd ~/www
composer require thunder/thunder-distribution:dev-${BRANCH_NAME} ${ADDITIONAL_PHP_PACKAGES}

# Set other requirements
mkdir -p ~/www/config/sync
