#!/bin/bash
#
# Test Thunder PHP image

# Maximum wait time in seconds (15 mins)
MAX_WAIT=900

# Prepare max wait time
CURRENT_TIMESTAMP=$(date +%s)
WAIT_UNTIL_TIMESTAMP=$((CURRENT_TIMESTAMP + MAX_WAIT))

# Wait for server to be ready
until $(curl --output /dev/null --silent --head --fail "http://${THUNDER_HOST}:8080/"); do
    if [ $(date +%s) -gt ${WAIT_UNTIL_TIMESTAMP} ]; then
      echo "Max time excided"
      exit 1
    fi

    printf '.'
    sleep 10
done

# Check that homepage is returned correctly
curl -s "http://${THUNDER_HOST}:8080/" | grep -q "meta.*Generator.*Thunder"
